name: Deployment
run-name: ${{ github.actor }} is deploying to Strato 🚀
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: ../hsh_homepage
          remote_path: /hendrik/
          remote_host: ssh.strato.de
          remote_port: 22
          remote_user: hendriksh@hendrik-sh.de
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_key_pass: ${{ secrets.REMOTE_PASSPHRASE }}
