name: Deployment
run-name: ${{ github.actor }} is deploying to Strato 🚀
on: [push]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Upload
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ssh.strato.de
          remote-user: hendriksh@hendrik-sh.de
          private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          destination-path: ~/hendrik/
