name: Deployment
run-name: ${{ github.actor }} is deploying to Strato 🚀
on: [push]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Upload
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.strato.de
          username: hendriksh@hendrik-sh.de
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ~/hendrik/
