name: Deployment
run-name: ${{ github.actor }} is deploying to Strato 🚀
on: [push]
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Upload FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          target-server: ssh.strato.de
          username: hendriksh@hendrik-sh.de
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          destination-path: ~/hendrik/
          port: 22
